### ISSUE TITLE
Create <Endpoint /> Component

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/PDK#10]
Create component to render via props the attributes:

- Header
- Params
- URL
- Method
- Description

**Comment by abdiangel** [comment]
This is how it looks when description, method and url is pulled from .json file
![captura de pantalla de 2018-03-20 03-03-55](https://user-images.githubusercontent.com/27755414/37640617-de97de12-2bec-11e8-90e0-31d16b2e6b0c.jpg)

**Comment by CharlyJazz** [comment]
Perfect, U could work in the validation data rendering

**Comment by abdiangel** [comment]
![captura de pantalla de 2018-03-21 01-45-15](https://user-images.githubusercontent.com/27755414/37695999-c64b4f34-2ca9-11e8-9d5e-067c235d05b4.png)
Now the whole data is being displayed, depending on its existence  in .json file
