### ISSUE TITLE
Create JSON with the API data

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/PDK#12]
- [x] Name -> String
- [x] Description -> String
- [x] API Version -> String
- [x] Path -> String
- [x] Protocol -> String
- [x] Endpoint -> Array of Object
    - [x] Description
    - [x] URL
    - [x] Method
    - [x] Request Header
    - [x] Request Params

**Comment by extrasad** [comment]
There is no such thing as "description" in the API data. Also, in some cases, there is no request header or request params data. I handle this cases by adding the following format: Request Header : "".
The method property sometimes, besides the method parameter, has a text: "testing with postman" , however, i didn't put this text, just put the method. Comment about this so i can fix it if there's some trouble.

**Comment by CharlyJazz** [comment]
Keep the values empty if they do not exist. "Header": ""

The description is the first thing that says the document about the
endpoint, example "Create new User"

2018-03-19 0:40 GMT-04:00 Carlos Rivas <notifications@github.com>:
