### ISSUE TITLE
Gatsby es una mierda hay que migrar HAHAHAHA

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/PDK#28]
![image](https://user-images.githubusercontent.com/12489333/37714820-e0a1a350-2cf0-11e8-9d9c-65dffb0860be.png)

**Comment by abdiangel** [comment]
My friend I don't understand what u mean with "gatsby es una meirda y hay que migrar" what are we gonna do now?

**Comment by CharlyJazz** [comment]
Migrate to wordpress site bacause react it's shit
